# Generated by Django 5.2.8 on 2025-11-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.FloatField(blank=True, help_text='Optional quantity', null=True),
        ),
    ]
