# Generated by Django 5.2.8 on 2025-11-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='servings',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, through='ingredients.RecipeIngredient', to='ingredients.ingredient'),
        ),
    ]
